# Generated by Django 5.0.2 on 2024-03-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
